### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by rillian** [alfredoyang/mp4parse_fallible#1]
Hi Alfredo.

Can we publish a version of this on crates.io? Not having that blocks updating the published mp4parse crate, which is less nice for servo and other users. I suggest we move this under the mozilla user (or into mozilla/mp4parse-rust as another included crate and publish to crates.io from there. I'm happy to do this if you prefer.

**Comment by alfredoyang** [comment]
Sure, never did it before but I'll study how to do.

**Comment by rillian** [comment]
I went ahead and did this, to unblock servo. I ran `cargo publish` from a new fork at [mozilla/mp4parse_fallible](https://github.com/mozilla/mp4parse_fallible).

If you make an account on crates.io, please let me know the username so I can add you as an owner.
